# Generated by Django 6.0.7 on 2026-07-21 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='4 lettres + 7 chiffres, ex: MSCU1234567', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Le nom du conteneur doit contenir exactement 4 lettres majuscules suivies de 7 chiffres (ex: MSCU1234567).', regex='^[A-Z]{4}\\d{7}$')])),
                ('taille', models.CharField(choices=[('20', '20 pieds'), ('40', '40 pieds')], max_length=2)),
                ('etat', models.CharField(choices=[('plein', 'Plein'), ('vide', 'Vide')], max_length=5)),
                ('statut', models.CharField(choices=[('entree', 'Entrée'), ('transfert', 'En transfert'), ('sortie_terrestre', 'Sortie terrestre'), ('sortie_maritime', 'Sortie maritime')], default='entree', max_length=20)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
