# Generated by Django 6.0.7 on 2026-07-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=2)),
                ('rangee', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1)),
                ('position', models.PositiveIntegerField()),
                ('conteneur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplacement', to='conteneurs.conteneur')),
            ],
            options={
                'ordering': ['zone', 'rangee', 'position'],
                'unique_together': {('zone', 'rangee', 'position')},
            },
        ),
    ]
