# Generated by Django 6.0.7 on 2026-07-21 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0002_emplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplacement',
            name='conteneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplacements', to='conteneurs.conteneur'),
        ),
    ]
