# Generated by Django 6.0.7 on 2026-07-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0003_alter_emplacement_conteneur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneur',
            name='statut',
            field=models.CharField(choices=[('entree', 'Entrée'), ('transfert', 'En transfert'), ('transfert_externe', 'Transfert externe'), ('sortie_terrestre', 'Sortie terrestre'), ('sortie_maritime', 'Sortie maritime')], default='entree', max_length=20),
        ),
    ]
